# Generated by Django 2.2.11 on 2020-05-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(null=True)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='upload.userfile')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
